<?php

namespace App\Bundles\ThemeBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;

class ThemeBundle extends Bundle {

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }



}